[package]
name = "eth-encode-packed"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethabi = "14.1.0"
hex = "0.4.3"
